name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Update system and install dependencies
      run: |
        sudo apt-get update && \
        sudo apt-get install -y python3.9 python3.9-distutils && \
        curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
        sudo python3.9 get-pip.py && \
        pip3 install -r requirements.txt && \
        python3.9 setup_nltk.py
          
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd 'Chat-On-Docs/' && \
          git pull origin master && \
          streamlit run app.py
