name: Deploy to EC2

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Update system
      run: |
        sudo apt-get update
	      sudo apt-get install python3 python3-pip -y

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
	      python3 setup_nltk.py

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd 'Chat-On-Docs/'
          git pull origin dev
          streamlit run app.py 
